//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.34209
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;

namespace AssemblyCSharp
{
	public class CollisionDetection : MonoBehaviour
	{
		public CollisionDetection ()
		{
			// Nothing to do
		}

		
		private void MyDelay(int seconds)
		{
			DateTime dt = DateTime.Now + TimeSpan.FromSeconds(seconds);
			
			do { } while (DateTime.Now < dt);
		}

		void OnCollisionEnter (Collision col)
		{
			var radius = 5.0f;
			var power = 10.0f;
			var collitionObject = col.gameObject; 

			//Debug.Log ("On colision with " + collitionObject.name);

			if (collitionObject.name.Equals("Blox")) {
				Vector3 explosionPos = transform.position;
				Collider[] colliders = Physics.OverlapSphere (explosionPos, radius);

				GenerateBlocks.CurrentScore++;
				//Debug.Log ("Scored (score is " + GenerateBlocks.CurrentScore);
				col.rigidbody.AddExplosionForce(power, explosionPos, radius, 3.0f);
				GenerateBlocks.DeleteCubeFromList(collitionObject);
			}
		}
	}
}

