//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.34209
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;

namespace AssemblyCSharp
{
	[RequireComponent(typeof(AudioSource))]
	public class CollisionDetection : MonoBehaviour
	{
		public AudioSource winAudio { set; get; }

		public CollisionDetection ()
		{
			// nothing todo
		}

		void OnCollisionEnter (Collision col)
		{
			var collitionObject = col.gameObject; 

			//Debug.Log ("On colision with " + collitionObject.name);

			if (collitionObject.name.Equals("Blox")) {
				Vector3 explosionPos = transform.position;

				GenerateBlocks.CurrentScore += 5;
				//Debug.Log ("Scored (score is " + GenerateBlocks.CurrentScore);
				GenerateBlocks.DeleteCubeFromList(collitionObject);
				var sound = GetComponents<AudioSource>();
				sound[0].Play();
			}
		}

	}
}

